const ErrorMessage = Object.freeze({
    MISSING_HEADERS: "MISSING_HEADERS",
    MISSING_PARAMETERS: "MISSING_PARAMETERS",
    INVALID_METHOD: "INVALID_METHOD",
    INVALID_SMS_CODE: "INVALID_SMS_CODE",
    DISABLED_USER: "DISABLED_USER",
    INVALID_USER: "INVALID_USER",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    PATH_VERIFY_ERROR: "PATH_VERIFY_ERROR",
    INVALID_TOKEN: "INVALID_TOKEN",
    SERVER_ERROR: "SERVER_ERROR",
    PHONE_NUMBER_EXISTS: "PHONE_NUM_EXISTS",
    VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
    PHOTO_NOT_FOUND: "PHOTO_NOT_FOUND"
});

export default ErrorMessage;